title: Deep Thoughts with Wesley
author: Wesley
theme: minima
email: wesley.j@simplepractice.com
description: > # this means to ignore newlines until "baseurl:"
  Thinkings and wonderings of a normal guy in LA.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
